# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    gemini_api_key_default: ''
    api_ninjas_key_default: ''
    huggingface_api_key_default: ''
    app.gemini_api_key: '%env(default:gemini_api_key_default:GEMINI_API_KEY)%'
    api_ninjas_key: '%env(default:api_ninjas_key_default:API_NINJAS_KEY)%'
    huggingface_api_key: '%env(default:huggingface_api_key_default:HUGGINGFACE_API_KEY)%'
    mercure_url: 'http://127.0.0.1:3000/.well-known/mercure'
    mercure_public_url: 'http://127.0.0.1:3000/.well-known/mercure'
    mercure_jwt_secret: '!ChangeThisMercureHubJWTSecretKey!'
    mercure_dsn: 'mercure://default'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $apiNinjasKey: '%api_ninjas_key%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\CommentaireInapproprieService:
        arguments:
            $apiKey: '%huggingface_api_key%'
  # -------- AJOUTEZ CECI --------
    App\Service\SentimentAnalysisService:
        arguments:
            $apiKey: '%huggingface_api_key%'


    App\Service\TranslationService:
        arguments:
            $client: '@http_client'
