# Stripe credentials - DO NOT commit real secrets
stripe.secret_key=your_stripe_secret_key_here
stripe.publishable_key=pk_test_51T2WRV2fFd8zzz2Lrn5sVAxvmew0spH46X2cs3T9a6ABUuWB36qpX5D3ZgXRbNyb01PCYdACF9NJ5SAN3EcdTBro00YpBjoTcU
stripe.default_currency=usd
