# Stripe credentials - DO NOT commit real secrets
stripe.secret_key=sk_test_51T2WRV2fFd8zzz2LuMZ1dFo3FPwOGA4y3Cb4s8sGyLLxYecwWeA5ckM6MLo9A2dwH8zyNlKvC7h133ksF3ZZDK3u00xRVS4eCS
stripe.publishable_key=pk_test_51T2WRV2fFd8zzz2Lrn5sVAxvmew0spH46X2cs3T9a6ABUuWB36qpX5D3ZgXRbNyb01PCYdACF9NJ5SAN3EcdTBro00YpBjoTcU
stripe.default_currency=usd
